# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

# 解決 Firebase Swift 依賴的 Static Library 問題
use_modular_headers!

# Enable New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '1'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'BestVersionOfYourself' do
  config = use_native_modules!

  # [FIX 1] 明確指定 gRPC 使用 Modular Headers (回應你的建議)
  pod 'gRPC-Core', :modular_headers => true
  pod 'gRPC-C++', :modular_headers => true

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'BestVersionOfYourselfTests' do
    inherit! :complete
    # Pods for testing
  end

  # [FIX 2] 終極解法：強制移除 gRPC-Core 的 Module Map 設定
  # 這能避免 Archive 時找不到 modulemap 檔案的錯誤
  pre_install do |installer|
    podspec = installer.pod_targets.find { |t| t.name == "gRPC-Core" }&.root_spec
    if podspec
        # 移除 MODULEMAP_FILE 設定，強迫 Xcode 使用傳統 Header Search Path
        podspec.pod_target_xcconfig["MODULEMAP_FILE"] = nil
    end
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react-native-pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # [FIX 3] 確保 gRPC 的標頭檔能被找到
    installer.pods_project.targets.each do |target|
      if target.name.start_with?('gRPC-C++') || target.name.start_with?('gRPC-Core')
        target.build_configurations.each do |config|
           config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
      end
    end
  end
end
